### PR TITLE
Added type hints to source code

### LINKED ISSUE #6: Convert script.js to Typescript
As the project gets bigger and more features get added and bugs get resolved, maintainability will get harder despite the functional programming structure of this project. If you want to collaborate with me on this, then reply to this issue.

### PR DESCRIPTION
**Pull request by pappurohit99**
- To avoid datatype related errors, I have added type check to JS file (@ts-check at top of file). IDEs like VSCode would throw warnings if there's a mismatch in datatype
- Restructured the code for better readability

***TO CONSIDER***
Porting the code to typescript might not be worth the effort. ts-check is a good enough linter

### CODE REVIEW

**Comment by VGBijpuria** [comment]
Actually I had migrated half the code base to TS after I had finished learning it 😅, I really don't want my effort to go to waste.

**Comment by pappurohit99** [comment]
> Actually I had migrated half the code base to TS after I had finished learning it 😅, I really don't want my effort to go to waste.

ts-check uses typescript engine to enforce typecasting. It makes it easier to maintain the code as the type needs to be mentioned in the JSDoc comments. We won't have to port to typescript using `node.js`. That would be a monumental effort with low value. Just a thought

**Comment by VGBijpuria** [comment]
> > Actually I had migrated half the code base to TS after I had finished learning it 😅, I really don't want my effort to go to waste.
> 
> ts-check uses typescript engine to enforce typecasting. It makes it easier to maintain the code as the type needs to be mentioned in the JSDoc comments. We won't have to port to typescript using `node.js`. That would be a monumental effort with low value. Just a thought

I don't think typing `npm install typescript` on one's local machine is a monumental effort. Comments pleading type safety can be safely ignored, while you can't do the same with a compiler angry at one. JSdoc requires the same amount of extra typing as TS. So, I think best solution for us will be to add comments (about general workings) to CS while having Typescript, what do you think about this?

**Comment by pappurohit99** [comment]
Alright, let's port to typescript.
First let's merge this change, as I added a quite a lot of null checks to improve robustness of the code. We can take up typescript in the next PR. Should be one time exercise

**Pull request merged**
