### PR TITLE
make mobile responsive

### PR DESCRIPTION
**Pull request by Axorax**

### CODE REVIEW

**Comment by VGBijpuria** [comment]
@Axorax I thoroughly tested your branch, and the design breaks when the link to call Bootstrap (through CDN) is removed. Isn't the whole point of this PR is to remove Bootsrap and make stuff look better (like in your design).

**Comment by Axorax** [comment]
> @Axorax I thoroughly tested your branch, and the design breaks when the link to call Bootstrap (through CDN) is removed. Isn't the whole point of this PR is to remove Bootsrap and make stuff look better (like in your design).

No. The point is to make the UI look better, not remove bootstrap.

I also made it mobile responsive. But the UI works along with bootstrap, not as a replacement. 

I think you merging the previous PR and reverting it introduced some conflicts. Might need to handle those to merge this PR.

**Comment by VGBijpuria** [comment]
No need to worry about the conflicts, I will resolve them. Just fix the footer for mobile (its broken there), I will merge this brach with main.

**Comment by Axorax** [comment]
> No need to worry about the conflicts, I will resolve them. Just fix the footer for mobile (its broken there), I will merge this brach with main.

All fixed and working as expected!

image
image

**Pull request merged**
