### PR TITLE
Solves issue 30#

### PR DESCRIPTION
**Pull request by ThuanTheSecond**
- Add element div class="popup_saved" in index.html
- Add code to decorate the popup in stylesheet.css
- Add code to show the popup when the click save button in script.js and script.ts
- P/S: Because I use Prettier on my VSCode, the script.js file was automatically formatted.

### CODE REVIEW

**Comment by ThuanTheSecond** [comment]
Here is my result.
Screenshot 2024-11-11 162952

**Comment by VGBijpuria** [comment]
There are some issues that have happened on my local machine-

https://github.com/user-attachments/assets/4d15f200-7952-444c-b909-0e1845708160

**Comment by ThuanTheSecond** [comment]
My bad, in index.html, I kept your import "script.min.js" and "stylesheet.min.css". Should I change the import to "script.js" and "stylesheet.css" or create my own js and css file then import?

**Comment by VGBijpuria** [comment]
@ThuanTheSecond If that's the issue, then no need to do anything, I will minify script.js and stylesheet.css myself and test. Your PR  is showing conflict because I had just passed a commit that added 1 line in all the conflicting files. You can ignore that conflict as it is unimportant to this PR.

**Comment by ThuanTheSecond** [comment]
Thank you

**Pull request merged**
