### PR TITLE
BUG RESOLVED

### PR DESCRIPTION
**Pull request by PartishtaP**
### **THE ISSUE HAS BEEN FIXED AND THE CHANGES MADE OR FIXED WERE**
** Fixed the line width issue (now lines with 0 width won't be visible).
Fixed the color reset issue (ensures the color does not reset to black).
Handled canvas updates properly when resizing or interacting.**

### CODE REVIEW

**Comment by VGBijpuria** [comment]
Just asking, do you want to be a collaborater of this project along with me?

**Comment by PartishtaP** [comment]
Yes I want to be a collaborator

**Comment by PartishtaP** [comment]
Please add me in the collaborator list

**Comment by PartishtaP** [comment]
Yes, I want to be a collaborator.
Please add me in the collaborator list

**Comment by VGBijpuria** [comment]
Sent you the invite

**Pull request merged**
